### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by SpaceCat2021** [SpaceCat2021/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by SpaceDog2021** [comment]
I would like to see how you accomplish this task and how I can help you)))  I'm 24 hours in touch and ready to answer all your questions ;)

**Comment by SpaceCat2021** [comment]
> I would like to see how you accomplish this task and how I can help you))) I'm 24 hours in touch and ready to answer all your questions ;)

Thank very much
