### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by SpaceCat2021** [SpaceCat2021/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by SpaceDog2021** [comment]
Oh, unfortunately I'm not have social networks. So sorry (((

**Comment by SpaceCat2021** [comment]
> Oh, unfortunately I'm not have social networks. So sorry (((
It's very sad, but it won't be a problem for me
